//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlteredObject
    {
        public int ActivityId { get; set; }
        public int AlteredObjectId { get; set; }
        public int ObjectId { get; set; }
        public string Alteration { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Object Object { get; set; }
    }
}
