//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentId { get; set; }
        public Nullable<int> RequerimentId { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public int Programmer { get; set; }
        public Nullable<int> AsignedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Requeriment Requeriment { get; set; }
    }
}
